meta_product_name: "Ski in"
meta_title: "Ski in - Create your perfect ski journey"
meta_description: "Find someone to ski and have fun with !"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
